# Generated by Django 4.0.4 on 2022-05-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_utomatic_is_active', models.BooleanField(default=False)),
                ('integration_frequency', models.CharField(choices=[('day', 'day'), ('two_day', 'two_day'), ('week', 'week')], max_length=50)),
            ],
        ),
    ]
