# Generated by Django 4.0.4 on 2022-05-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsettings',
            name='integration_frequency',
            field=models.CharField(choices=[('day', 'day'), ('two_day', 'two_day'), ('week', 'week')], default='day', max_length=50),
        ),
    ]
