# Generated by Django 4.0.4 on 2022-05-06 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_integrationsettings_integration_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integrationsettings',
            old_name='integration_utomatic_is_active',
            new_name='integration_automatic_is_active',
        ),
    ]
