# Generated by Django 4.0.4 on 2022-05-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_user_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationsettings',
            name='integration_automatic_is_active',
        ),
        migrations.RemoveField(
            model_name='integrationsettings',
            name='integration_frequency',
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='frequenc',
            field=models.CharField(choices=[('day', 'day'), ('two_day', 'two_day'), ('week', 'week')], default='day', max_length=50, verbose_name='frequenc'),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='time',
            field=models.TimeField(default='00:00:00', verbose_name='time'),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='type',
            field=models.BooleanField(default=False, verbose_name='Type'),
        ),
    ]
