# Generated by Django 4.0.4 on 2022-05-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_integrationsettings_integration_automatic_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsettings',
            name='time',
            field=models.TimeField(default='00:00:00', null=True, verbose_name='time'),
        ),
    ]
