# Generated by Django 4.0.4 on 2022-05-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_integrationsettings_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsettings',
            name='type',
            field=models.CharField(choices=[('automatic', 'automatic'), ('manual', 'manual')], default=False, max_length=50, verbose_name='Type'),
        ),
    ]
