# Generated by Django 4.0.4 on 2022-05-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_integrationsettings_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsettings',
            name='frequenc',
            field=models.CharField(choices=[('day', 'day'), ('two_days', 'two days'), ('week', 'week')], max_length=50, verbose_name='frequenc'),
        ),
        migrations.AlterField(
            model_name='integrationsettings',
            name='type',
            field=models.CharField(choices=[('automatic', 'automatic'), ('manual', 'manual')], max_length=50, verbose_name='Type'),
        ),
    ]
