# Generated by Django 4.0.4 on 2022-05-17 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_integrationsettings_frequenc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 14, 1, 21, 809742), verbose_name='update date'),
        ),
    ]
