# Generated by Django 4.0.4 on 2022-05-17 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_integrationsettings_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsettings',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 14, 3, 22, 169658), verbose_name='update date'),
        ),
    ]
