# Generated by Django 4.0.4 on 2022-05-17 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_integrationsettings_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsettings',
            name='update_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='update date'),
        ),
    ]
