# Generated by Django 4.0.4 on 2022-05-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_integrationsettings_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsettings',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='update date'),
        ),
    ]
