# Generated by Django 4.0.4 on 2022-05-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_integrationsettings_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('table', models.CharField(choices=[('customer', 'customer'), ('finance', 'finance')], max_length=50, verbose_name='Table')),
                ('status', models.CharField(choices=[('customer', 'customer'), ('finance', 'finance')], max_length=50, verbose_name='Table')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Datetime')),
            ],
        ),
    ]
