# Generated by Django 4.0.4 on 2022-05-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_integrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrations',
            name='status',
            field=models.CharField(choices=[('customer', 'customer'), ('finance', 'finance')], max_length=50, verbose_name='Status'),
        ),
    ]
