# Generated by Django 4.0.4 on 2022-05-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_integrations_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrations',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('erreur', 'erreur')], max_length=50, verbose_name='Status'),
        ),
    ]
