# Generated by Django 4.0.4 on 2022-05-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_integrations_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrations',
            name='description',
            field=models.CharField(default='description', max_length=50, verbose_name='Description'),
        ),
    ]
