# Generated by Django 4.0.4 on 2022-05-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_integrations_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrations',
            name='description',
            field=models.CharField(default='description', max_length=350, verbose_name='Description'),
        ),
    ]
