# Generated by Django 3.2.13 on 2022-06-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_integrations_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='email_reporting',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
