# Generated by Django 3.2.13 on 2022-06-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_integrationsettings_email_reporting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsettings',
            name='email_reporting',
            field=models.EmailField(max_length=254),
        ),
    ]
