# Generated by Django 3.2.13 on 2022-06-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_integrationsettings_email_reporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='email_conix_reporting',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='email_conix_reporting_psw',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
