# Generated by Django 3.2.13 on 2022-06-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20220607_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrations',
            name='table',
        ),
        migrations.RemoveField(
            model_name='integrations',
            name='title',
        ),
        migrations.AlterField(
            model_name='integrations',
            name='date_time',
            field=models.DateTimeField(verbose_name='Datetime'),
        ),
    ]
