# Generated by Django 3.2.13 on 2022-06-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20220609_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrations',
            name='description',
            field=models.CharField(default='description', max_length=550, verbose_name='Description'),
        ),
    ]
