# Generated by Django 3.2.13 on 2022-06-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_integrations_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrations',
            name='type',
            field=models.CharField(choices=[('automatic', 'automatic'), ('manual', 'manual')], default=None, max_length=50, verbose_name='Type'),
        ),
    ]
