# Generated by Django 3.2.13 on 2022-06-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_integrations_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrations',
            name='type',
            field=models.CharField(choices=[('automatic', 'automatic'), ('manual', 'manual')], max_length=50, verbose_name='Type'),
        ),
    ]
