# Generated by Django 3.2.13 on 2022-06-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_integrations_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='email_host',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='email_port',
            field=models.IntegerField(default=None),
        ),
    ]
