# Generated by Django 3.2.13 on 2022-06-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20220616_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integrationsettings',
            old_name='email_conix_reporting_psw',
            new_name='smtp_password',
        ),
        migrations.RenameField(
            model_name='integrationsettings',
            old_name='email_port',
            new_name='smtp_port',
        ),
        migrations.RenameField(
            model_name='integrationsettings',
            old_name='email_host',
            new_name='smtp_server',
        ),
        migrations.RenameField(
            model_name='integrationsettings',
            old_name='email_conix_reporting',
            new_name='smtp_user',
        ),
    ]
